AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Gemspec/RequireMFA: # todo
  Enabled: false
Gemspec/RequiredRubyVersion: # todo
  Enabled: false
Style/Documentation: # todo
  Enabled: false
